#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#
# Copyleft (c) by Denis Astahov
#--------------------------------------------------------------
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID    : "180934650193"
    ECR_REPO_NAME     : "yom"
    ECR_IMAGE_TAG     : "latest"

phases:
  install:
    commands:
      - echo "Check aws and git version"
      - aws --version
      - git --version
      
  pre_build:
    commands:
      - echo "Login to AWS ECR and get commit id"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 180934650193.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_ID=$(git rev-parse --short HEAD)
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t yom:latest . 
      - docker tag yom:latest 180934650193.dkr.ecr.us-east-1.amazonaws.com/yom:latest
      - docker tag yom:latest 180934650193.dkr.ecr.us-east-1.amazonaws.com/yom:COMMIT_ID
   
      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 180934650193.dkr.ecr.us-east-1.amazonaws.com/yom:latest
      - docker tag yom:latest 180934650193.dkr.ecr.us-east-1.amazonaws.com/yom:COMMIT_ID
       # Создание артефакта с информацией о задаче и URI образа
     
